Melhorias na detecção de test smells CTL e na detecção de arquivos ".py".
danieldavidf/TEMPY pull request #1
Opened 2023-12-03 15:07 UTC by tassiovirginio

A versão que eu estava rodando estava detectando arquivos do tipo ".pyc". E coloquei para o sistema não detectar instruções "for" que tivessem na sua próxima linha a instrução "subTest".

2023-12-03 22:25 UTC, danieldavidf requested changes

2023-12-03 22:25 UTC, danieldavidf commented on report/log.html
Você acabou comitando com o arquivo de report junto

2023-12-03 22:25 UTC, danieldavidf commented on assets/detector.py
> +						source.content[i].lstrip().find("if ") == 0 or
o método lstrip() remove espaços em branco e quebra de linhas de string. Portanto o espaço em branco nunca será encontrado numa string que passou por esse método. Entendi que você quis englobar condicionais que não tenham parenteses, uma possível sintaxe no Python. Para resolver isso acho melhor buscar por : no final da linha.

2023-12-03 22:25 UTC, danieldavidf commented on report/log.html
uma ideia seria incluir arquivos dentro do report no .gitignore

2023-12-03 22:35 UTC, tassiovirginio commented on assets/detector.py
> +						source.content[i].lstrip().find("if ") == 0 or
EU segui o exemplo que você tinha colocado do "while", lstrip() no caso remove os espaços vazios do começo e final da string, pelo que vi nos exemplos na internet, então ele consegue achar um "if ", ou não?

2023-12-03 23:15 UTC, danieldavidf commented on assets/detector.py
> +						source.content[i].lstrip().find("if ") == 0 or
se deixar apenas "if " ele vai procurar por "if" e isso causaria falsos-positivos em caso de uma variável ou o nome de um método ter um if no meio.

2023-12-04 00:46 UTC, tassiovirginio commented on main.py
> +				if (x.endswith('.py') and x.find( 'main.py' )==-1):
alterei essa parte para não detectar arquivos ".pyc"

2023-12-16 13:16 UTC, closed without merging